MyBlog/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls.py),
    path('', include('news.urls')),
    path('user/', include('users.urls')),
    path('', include('verifications.urls')),
    path('doc/', include('doc.urls')),
    path('course/', include('course.urls')),
    path('admin/', include('admin.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/course/urls.py
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course_list, name='index'),
    path('<int:course_id>/', views.CourseDetailView.as_view(), name='course_detail')
]

apps/course/models.py
from django.db import models
from utils.models import BaseModel


# 老师表
class Teacher(BaseModel):
    name = models.CharField('讲师姓名', max_length=150, help_text='讲师姓名')
    title = models.CharField('职称', max_length=150, help_text='职称')
    profile = models.TextField('简介', help_text='简介')
    photo = models.URLField('头像url', default='', help_text='头像url')

    class Meta:
        db_table = 'tb_teachers'
        verbose_name = '讲师'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 课程分类表
class CourseCategory(BaseModel):
    name = models.CharField('课程分类名', max_length=100, help_text='课程分类名')

    class Meta:
        db_table = 'tb_course_category'
        verbose_name = '课程分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 课程表
class Course(BaseModel):
    title = models.CharField('课程名', max_length=150, help_text='课程名')
    cover_url = models.URLField('封面url', help_text='封面url')
    video_url = models.URLField('课程视频url', help_text='课程视频url')
    duration = models.DurationField('课程时长', help_text='课程时长')
    profile = models.TextField('课程简介', null=True, blank=True, help_text='课程简介')
    outline = models.TextField('课程大纲', null=True, blank=True, help_text='课程大纲')
    teacher = models.ForeignKey('Teacher', on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey('CourseCategory', on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        db_table = 'tb_course'
        verbose_name = '课程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

apps/course/views.py
from django.shortcuts import render, Http404
from django.views import View
from . import models


def course_list(request):
    """
    在线课程列表
    url:/course/
    :param request:
    :return:
    """
    courses = models.Course.objects.select_related('teacher').\
        only('title', 'cover_url', 'teacher__title', 'teacher__name').\
        filter(is_delete=False)
    return render(request, 'course/course.html', context={'courses': courses})


class CourseDetailView(View):
    """
    课程详情视图
    url:/course/<int:course_id>/
    """
    def get(self, request, course_id):
        course = models.Course.objects.only(
            'title', 'cover_url', 'video_url',
            'profile', 'outline', 'teacher__name',
            'teacher__photo', 'teacher__title', 'teacher__profile').\
            select_related('teacher').filter(is_delete=False, id=course_id).first()
        if course:
            return render(request, 'course/course_detail.html', context={'course': course})
        else:
            return Http404('此课程不存在')

templates/course/course.html
<!-- 创建模板templates/course/course.html -->
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
  在线课堂
{% endblock %}
{% block link %}
 <link rel="stylesheet" href="{% static 'css/course/course.css' %}">
{% endblock %}
{% block main_start %}
 <main id="course-container">
        <div class="w1200">
            <ul class="course-list">
                {% for course in courses %}
                    <li class="course-item">
                    <a href="{% url 'course:course_detail' course.id %}">
                        <img class="course-img" src="{{ course.cover_url }}"
                            alt="{{ course.title }}">
                        <div class="course-content">
                            <p class="course-info">{{ course.title }}</p>
                            <p class="course-author">{{ course.teacher.name}}({{ course.teacher.title }})</p>
                            <p class="course-price free">免费</p>
                        </div>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </main>
{% endblock %}

templates/course/course_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}视频详情-{{ course.title }}{% endblock %}
{% block link %}
    <link rel="stylesheet" href="{% static 'css/course/course-detail.css' %}">
{% endblock %}
{% block main_start %}
    <main id="main">
        <div class="w1200">
            <div class="course-contain">
                <div class="course-top-contain">
                    <h4 class="course-title">{{ course.title }}</h4>
                    <div class="course-other clearfix">
                        <div class="share">
                             <i></i>
                            <span>分享</span>
                            <div class="share-list">
                                    <div class="bshare-custom icon-medium"><div class="bsPromo bsPromo2"></div><a title="分享到QQ空间" class="bshare-qzone"></a><a title="分享到新浪微博" class="bshare-sinaminiblog"></a><a title="分享到QQ好友" class="bshare-qqim" href="javascript:void(0);"></a><a title="分享到微信" class="bshare-weixin" href="javascript:void(0);"></a><a title="更多平台" class="bshare-more bshare-more-icon more-style-addthis"></a><span class="BSHARE_COUNT bshare-share-count" style="float: none;">62.9K</span></div><script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/buttonLite.js#style=-1&amp;uuid=&amp;pophcol=2&amp;lang=zh"></script><script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/bshareC0.js"></script>
                            </div>
                        </div>
                        <div class="buy-list">
                            <span class="price">免费</span>
                        </div>
                    </div>
                </div>

                <div class="course-video" id="course-video">
                    <span class="course-data" style="display: none" data-video-url="{{ course.video_url }}"
                          data-cover-url="{{ course.cover_url }}"></span>
                </div>

                <div class="course-bottom-contain">
                    <div class="course-detail-list">
                        <div class="course-item clearfix">
                            <h5 class="course-title">{{ course.teacher.name }}</h5>
                            <div class="teacher-box clearfix">
                                <img src="{{ course.teacher.photo }}" alt="{{ course.teacher.name }}"
                                     title="{{ course.teacher.name }}" class="teacher-avatar">
                                <div class="teacher-info">
                                    <p class="teacher-name">{{ course.teacher.name }}</p>
                                    <p class="teacher-identify"> {{ course.teacher.title }}</p>
                                </div>
                            </div>
                            <div class="item-content">
                                {{ course.teacher.profile }}
                            </div>
                        </div>
                        <div class="course-item clearfix">
                            <h5 class="course-title">课程简介</h5>
                            <div class="item-content">
                                {{ course.profile }}
                            </div>
                        </div>
                        <div class="course-item clearfix">
                            <h5 class="course-title">课程大纲</h5>
                            <div class="item-content">
                                <p>{{ course.outline }}</p>
                            </div>
                        </div>
                        <div class="course-item clearfix">
                            <h5 class="course-title">帮助中心</h5>
                            <div class="item-content">
                                <p>1. 购买后的课程在线可反复观看学习，视频有效期以具体课程信息为准。 </p>
                                <p>2. 课程暂不支持下载观看，均为在线观看视频。 </p>
                                <p>3. 课程一经购买，不可转让、不可退款；仅限购买账号观看。</p>
                                <p>4. 如有问题请咨询客服: 400-1567-315 </p>
                            </div>
                        </div>
                        <div class="course-item clearfix">
                            <h5 class="course-title">关于潭州课堂</h5>
                            <div class="item-content">
                                湖南潭州教育网络科技有限公司拥有千余人的优秀师资团队，是一家师资丰富、教育产品类别众多的在线培训公司。公司总部座落于美丽的星城长沙，2015年9月正式入驻芯城科技园目前拥有近两万平米办公面积。
                                在潭州学习的学员已突破1000万人次在线学员覆盖全球，包括中国、加拿大、日本、美国、韩国等诸多国家。
                            </div>
                        </div>

                    </div>
                    <div class="course-side">
                        <h4 class="side-title">推荐课程</h4>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}
{% block script %}
    <script src="https://cdn.bdstatic.com/jwplayer/latest/cyberplayer.js"></script>
    <script src="{% static 'js/course/course_detail.js' %}"></script>
{% endblock %}