MyBlog/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls.py),
    path('', include('news.urls')),
    path('user/', include('users.urls')),
    path('', include('verifications.urls')),
    path('doc/', include('doc.urls')),
    path('course/', include('course.urls')),
    path('admin/', include('admin.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/news/urls.py
from django.urls import path
from . import views
# url的命名空间
app_name = 'news'
# <a href="{% url 'news:index' %}"></a>
urlpatterns = [
    path('', views.index, name='index'),    # 将这条路由命名为index
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/banners/', views.NewsBannerView.as_view(), name='news_banner'),
    path('news/<int:news_id>/', views.NewDetailView.as_view(), name='news_detail'),
    path('news/<int:news_id>/comment/', views.NewsCommentView.as_view(), name='news_comment'),
    path('search/', views.NewsSearchView.as_view(), name='news_search'),
    # path('search/', views.NewsSearchView.as_view(), name='search'),
]

apps/news/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from utils.models import BaseModel


class Tag(BaseModel):
    """
    文章分类标签模型
    """
    name = models.CharField('标签名', max_length=64, help_text='标签名')

    class Meta:
        ordering = ['-update_time', '-id']      # 排序
        db_table = "tb_tag"                     # 指明数据库表名
        verbose_name = "文章标签"                # 在admin站点中显示的名称
        verbose_name_plural = verbose_name      # 显示的复数名称

    def __str__(self):
        return self.name


class News(BaseModel):
    """
    文章模型
    """
    title = models.CharField('标题', max_length=150, validators=[MinLengthValidator(1), ], help_text='标题')
    digest = models.CharField('摘要', max_length=200, validators=[MinLengthValidator(1), ], help_text='摘要')
    content = models.TextField('内容', help_text='内容')
    clicks = models.IntegerField('点击量', default=0, help_text='点击量')
    image_url = models.URLField('图片url', default='', help_text='图片url')
    # 一对多 外键在多的这一个键，一为主表，多为子表
    # CASCADE   级联，主表一删除，子表也删除
    # PROTECT   主表一删，子表报错
    # SET_NULL  主表一删，子表相对应数据设置为null，同时设置null=True
    # SET_DEFAULT   主表一删，子表相对应数据设置为默认值，同时设置default=xx,
    # SET   # 指定一个可调用对象，函数返回的值赋给子表
    tag = models.ForeignKey('Tag', on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey('users.Users', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['-update_time', '-id']  # 排序
        db_table = "tb_news"  # 指明数据库表名
        verbose_name = "新闻"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return self.title


class Comments(BaseModel):
    """
    评论模型
    """
    content = models.TextField('内容', help_text='内容')
    author = models.ForeignKey('users.Users', on_delete=models.SET_NULL, null=True)
    news = models.ForeignKey('News', on_delete=models.CASCADE)
    # 本项目设计二级评论，修改Comments模型，添加一个parent字段
    # null 是针对数据库而言，如果 null=True, 表示数据库的该字段可以为空，那么在新建一个model对象的时候是不会报错的！！
    # blank 是针对表单的，如果 blank=True，表示你的表单填写该字段的时候可以不填，比如 admin 界面下增加 model 一条记录的时候。直观的看到就是该字段不是粗体。
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ['-update_time', '-id']  # 排序
        db_table = "tb_comments"  # 指明数据库表名
        verbose_name = "评论"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def to_dict(self):
        comment_dict = {
            'news_id': self.news.id,
            'comment_id': self.id,
            'content': self.content,
            'author': self.author.username,
            'update_time': self.update_time.strftime('%Y年%m月%d日 %H:%M'),
            'parent': self.parent.to_dict() if self.parent else None,
        }
        return comment_dict

    def __str__(self):
        return '<评论{}>'.format(self.id)


class HotNews(BaseModel):
    """
    推荐文章表
    """
    PRI_CHOICES = [
        (1, '第一级'),
        (2, '第二级'),
        (3, '第三级')
    ]
    news = models.OneToOneField('News', on_delete=models.CASCADE)
    priority = models.IntegerField(verbose_name='优先级', help_text='优先级', choices=PRI_CHOICES, default=3)

    class Meta:
        ordering = ['priority', '-update_time', '-id']  # 排序
        db_table = "tb_hotnews"  # 指明数据库表名
        verbose_name = "热门新闻"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return '<热门新闻{}>'.format(self.id)


class Banner(BaseModel):
    """
    轮播图
    """
    PRI_CHOICES = [
        (1, '第一级'),
        (2, '第二级'),
        (3, '第三级'),
        (4, '第四级'),
        (5, '第五级'),
        (6, '第六级'),
    ]
    image_url = models.URLField(verbose_name='轮播图url', help_text='轮播图url')
    priority = models.IntegerField(verbose_name='优先级', help_text='优先级', choices=PRI_CHOICES, default=6)

    news = models.OneToOneField('News', on_delete=models.CASCADE)

    class Meta:
        ordering = ['priority', '-update_time', '-id']  # 排序
        db_table = "tb_banner"  # 指明数据库表名
        verbose_name = "轮播图"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return '<轮播图{}>'.format(self.id)

apps/news/views.py
import logging
import json
from django.http import HttpResponseNotFound, Http404
from django.shortcuts import render
from django.views import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import F

from haystack.generic_views import SearchView
import MyBlog.settings as settings
from .models import Tag, News, Banner, HotNews, Comments
from . import constants
from utils.json_res import json_response
from utils.res_code import *

logger = logging.getLogger('django')


# Create your views here.
def index(request):
    """
    新闻首页视图
    url: /
    :param request:
    :return:
    """
    # 只取这几个
    tags = Tag.objects.only('id', 'name').filter(is_delete=False)
    # 排除这几个
    # tags = Tag.objects.defer('create_time', 'update_time', 'is_delete').filter(is_delete=False)
    hot_news = HotNews.objects.select_related('news').\
        only('news__title', 'news__image_url', 'news_id').\
        filter(is_delete=False).\
        order_by('priority', '-news__clicks')[:constants.SHOW_HOTNEWS_COUNT]
    return render(request, 'news/index.html',
                  context={
                      'tags': tags,
                      'hot_news': hot_news
                  })
    # locals() 包括所有属性
    # return render(request, 'news/base.html',
    #                   locals())


class NewsListView(View):
    """
    新闻列表视图
    url: /news/
    args: tag, page
    """
    def get(self, request):
        # 1. 判断前端传递标签分类id是否为空，是否为整数，是否超过范围
        # 2. 判断前端传递当前文章页数是否为空，是否为整数，是否超过范围
        try:
            tag_id = int(request.GET.get('tag', 0))
        except Exception as e:
            logger.error('标签错误：\n{}'.format(e))
            tag_id = 0

        try:
            page = int(request.GET.get('page', 1))
        except Exception as e:
            logger.error('页码错误：\n{}'.format(e))
            page = 1
        # 使用only返回的是对象，所以传递到前端时需要迭代处理
        news_queryset = News.objects.select_related('tag', 'author').only(
            'title', 'digest', 'image_url', 'update_time', 'tag__name', 'author__username')
        # values 返回字典
        # news_queryset = News.objects.values('id', 'title', 'digest', 'image_url', 'update_time'). \
        #     annotate(tag_name=F('tag__name'), author=F('author__username'))

        news = news_queryset.filter(is_delete=False, tag_id=tag_id) or \
            news_queryset.filter(is_delete=False)

        paginator = Paginator(news, constants.PER_PAGE_NEWS_COUNT)
        try:
            # 获取页面数据 get_page可以容错
            news_info = paginator.get_page(page)
        except EmptyPage:
            logging.info("用户访问的页数大于总页数")
            news_info = paginator.get_page(paginator.num_pages)
        # 序列化数据
        news_info_list = []
        for n in news_info:
            news_info_list.append({
                'id': n.id,
                'title': n.title,
                'digest': n.digest,
                'image_url': n.image_url,
                'tag_name': n.tag.name,
                'author': n.author.username,
                'update_time': n.update_time.strftime('%Y年%m月%d日 %H:%M')
            })
        data = {
            'total_pages': paginator.num_pages,
            'news': news_info_list
            # 'news': list(news_info)
        }
        return json_response(data=data)


class NewsBannerView(View):
    """
    轮播图视图
    url:/news/banners/
    """
    def get(self, request):
        # banners = Banner.objects.values('image_url', 'news_id').annotate(
        #     news_title=F('news__title')
        # ).filter(is_delete=False)[:constants.SHOW_BANNER_COUNT]
        banners = Banner.objects.select_related('news').\
                      only('image_url', 'news_id', 'news__title').\
                      filter(is_delete=False)[:constants.SHOW_BANNER_COUNT]
        # 序列化输出
        banners_info_list = []
        for b in banners:
            banners_info_list.append({
                'image_url': b.image_url,
                'news_id': b.news_id,
                'news_title': b.news.title
            })
        # 返回前端
        data = {
            'banners': banners_info_list
        }
        return json_response(data=data)


class NewDetailView(View):
    """
    新闻详情页
    route:  news/<int:news_id>/
    """
    def get(self, request, news_id):
        news = News.objects.select_related('tag', 'author').\
            only('title', 'content', 'update_time', 'tag__name', 'author__username').\
            filter(is_delete=False, id=news_id).first()
        if news:
            # 返回json需要序列化
            # 返回模版渲染不需要
            comments = Comments.objects.select_related('author', 'parent').\
                only('content', 'author__username', 'update_time',
                     'parent__author__username', 'parent__content',
                     'parent__update_time').\
                filter(is_delete=False, news_id=news_id)
            # 序列化输出
            comments_list = []
            for comm in comments:
                comments_list.append(comm.to_dict())
            return render(request, 'news/news_detail.html', context={
                'news': news,
                'comments': comments
            })
        else:
            # raise Http404("<h1>Page not found</h1>")
            return HttpResponseNotFound('<h1>Page not found</h1>')
        # 快捷方式
        # 1. 去数据库获取新闻数据
        # news_queryset = News.objects.select_related('tag', 'author').\
        # only('title', 'content', 'update_time', 'tag__name', 'author__username').\
        # filter(is_delete=False, id=news_id)
        # news = get_object_or_404(news_queryset, is_delete=False, id=news_id)

        # 2. 返回渲染页面
        # return render(request, 'news/news_detail.html', context={'news': news})


class NewsCommentView(View):
    """
    添加评论视图
    url: /news/<int:news_id>/comment/
    """
    def post(self, request, news_id):
        # 是否登录
        if not request.user.is_authenticated:
            return json_response(errno=Code.SESSIONERR, errmsg=error_map[Code.SESSIONERR])
        # 新闻是否存在
        if not News.objects.only('id').filter(is_delete=False, id=news_id).exists():
            return json_response(errno=Code.PARAMERR, errmsg='新闻不存在！')
        # 获取前端数据
        try:
            json_data = request.body
            if not json_data:
                return json_response(errno=Code.PARAMERR, errmsg="参数为空，请重新输入")
            dict_data = json.loads(json_data.decode('utf8'))
        except Exception as e:
            logger.info("错误信息，\n{}".format(e))
            return json_response(errno=Code.UNKOWNERR, errmsg=error_map[Code.UNKOWNERR])
        content = dict_data.get('content')
        # 内容是否为空
        if not content:
            return json_response(errno=Code.PARAMERR, errmsg='评论内容不能为空！')

        # 父id是否正常
        parent_id = dict_data.get('parent_id')
        if parent_id:
            try:
                # 判断是不是整数
                parent_id = int(parent_id)
                # 判断是否有父评论，父评论id是否与新闻id匹配
                if not Comments.objects.only('id').\
                        filter(is_delete=False, id=parent_id, news_id=news_id).exists():
                    return json_response(errno=Code.PARAMERR, errmsg=error_map[Code.PARAMERR])
            except Exception as e:
                logger.info('前端传递过来的parent_id异常\n{}'.format(e))
                return json_response(errno=Code.PARAMERR, errmsg='未知异常')

        # 保存到数据库
        new_comment = Comments()
        new_comment.content = content
        new_comment.news_id = news_id
        new_comment.author = request.user
        new_comment.parent_id = parent_id if parent_id else None
        new_comment.save()

        return json_response(data=new_comment.to_dict())


class NewsSearchView(SearchView):
    """
    新闻搜索视图
    """
    # 设置搜索模板文件
    template_name = 'news/search.html'

    # 重写get请求，如果请求参数q为空，返回模型News的热门新闻数据
    # 否则根据参数q搜索相关数据
    def get(self, request, *args, **kwargs):
        # 前端输入的查询参数
        query = self.request.GET.get('q', '')
        if not query:
            # 显示热门新闻
            show_hot = True
            hot_news = HotNews.objects.select_related('news').\
                only('news__title', 'news__image_url', 'news_id').\
                filter(is_delete=False).order_by('priority', '-news__clicks')
            paginator = Paginator(hot_news, settings.HAYSTACK_SEARCH_RESULTS_PER_PAGE)
            try:
                # 页码
                page = paginator.get_page(int(self.request.GET.get('page', 1)))
            except PageNotAnInteger:
                # 如果参数page不是整数型，就返回第一页的数据
                page = paginator.get_page(1)
            except EmptyPage:
                # 用户访问的页数大于实际页数，则返回最后一页
                page = paginator.page(paginator.num_pages)

            return render(self.request, self.template_name, context={
                'page': page,
                'paginator': paginator,
                'query': query,
                'show_hot': show_hot
            })
        else:
            show_hot = False
            # 搜索
            return super().get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        """
        在context中添加page变量
        :param args:
        :param kwargs:
        :return:
        """
        context = super().get_context_data(*args, **kwargs)
        if context['page_obj']:
            context['page'] = context['page_obj']
        return context

templates/news/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
  首页
{% endblock title %}
{% block link %}
  <link rel="stylesheet" href="{% static 'css/news/index.css' %}">
{% endblock link %}

{% block main_contain %}
  <div class="main-contain">
      <!-- banner start -->
        <div class="banner">
            <ul class="pic">
                <!--淡入淡出banner-->

            </ul>
            <a href="javascript:void(0);" class="btn prev">
                <i class="PyWhich py-arrow-left"></i></a>
            <a href="javascript:void(0);" class="btn next">
                <i class="PyWhich py-arrow-right"></i></a>
            <ul class="tab">
                <!-- 按钮数量必须和图片一致 -->

            </ul>
        </div>
      <!-- banner end -->

      <!-- content start -->
      <div class="content">
        <!-- recommend-news start -->
          <ul class="recommend-news">
            {% for hot_new in hot_news %}
              <li>
                  <a href="#" target="_blank">
                      <div class="recommend-thumbnail">
                          <img src="{{ hot_new.news.image_url }}" alt="title">
                      </div>
                      <p class="info">{{ hot_new.news.title }}</p>
                  </a>
              </li>
            {% endfor %}
          </ul>
        <!-- recommend-news end -->

        <!--  news-nav start-->
          <nav class="news-nav">
              <ul class="clearfix">
                  <li class="active"><a href="javascript:void(0)" data-id="0">最新资讯</a></li>
                  {% for tag in tags %}
                    <li><a href="javascript:void(0)" data-id="{{ tag.id }}">{{ tag.name }}</a>
                    </li>
                  {% endfor %}
              </ul>
          </nav>
        <!--  news-nav end -->

        <!-- news-contain start -->
          <div class="news-contain">
              <ul class="news-list">

              </ul>
          </div>
        <!-- news-contain end -->

        <!-- btn-more start -->
        <a href="javascript:void(0);" class="btn-more">加载更多</a>
        <!-- btn-more end -->
      </div>
      <!-- content end -->
    </div>
{% endblock main_contain %}

{% block script %}
  <script src="{% static 'js/news/index.js' %}"></script>
{% endblock script %}

templates/news/news_detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
  文章详情
{% endblock %}

{% block link %}
  <link rel="stylesheet" href="{% static 'css/news/news-detail.css' %}">
{% endblock %}

{% block main_contain %}
  <!-- news-contain start  -->
  <div class="news-contain">
    <h1 class="news-title">{{ news.title }}</h1>
    <div class="news-info">
      <div class="news-info-left">
        <span class="news-author">{{ news.author.username }}</span>
        <span class="news-pub-time">{{ news.update_time }}</span>
        <span class="news-type">{{ news.tag.name }}</span>
      </div>
    </div>
    {#   safe 转义   #}
    <article class="news-content">
      {{ news.content|safe }}
    </article>
    <!-- news comment start -->
    <div class="comment-contain">
      <div class="comment-pub clearfix">
        <div class="new-comment">
          文章评论(<span class="comment-count">0</span>)
        </div>
        {% if user.is_authenticated %}
          <div class="comment-control logged-comment" news-id="{{ news.id }}">
            <input type="text" placeholder="请填写评论">
          </div>
        {% else %}
          <div class="comment-control please-login-comment" news-id="{{ news.id }}">
            <input type="text" placeholder="请登录后参加评论" readonly>
          </div>
        {% endif %}
        <button class="comment-btn">发表评论</button>
        {% csrf_token %}
      </div>
      <!-- news comment end -->
      <ul class="comment-list">
        {% for comment in comments %}
          <li class="comment-item">
            <div class="comment-info clearfix">
              <img src="/static/images/avatar.jpeg" alt="avatar" class="comment-avatar">
              <span class="comment-user">{{ comment.author.username }}</span>
              <span class="comment-pub-time">{{ comment.update_time }}</span>
            </div>
            <div class="comment-content">{{ comment.content }}</div>
            {% if comment.parent %}
              <div class="parent_comment_text">
                <div class="parent_username">{{ comment.parent.author }}</div>
                <div class="comment_time">{{ comment.parent.update_time }}</div>
                <div class="parent_content_text">
                  {{ comment.parent.content }}
                </div>
              </div>
            {% endif %}
            <a href="javascript:void(0);" class="reply_a_tag right_float">回复</a>
            <form class="reply_form left_float" comment-id="{{ comment.id }}"
                  news-id="{{ comment.news_id }}">
              <textarea class="reply_input"></textarea>
              <input type="button" value="回复" class="reply_btn right_float">
              <input type="reset" name="" value="取消" class="reply_cancel right_float">
            </form>
          </li>
        {% endfor comments %}

      </ul>
    </div>

  </div>
  <!-- news-contain end  -->
{% endblock %}

{% block script %}
  <script src="{% static 'js/news/news_detail.js' %}"></script>
{% endblock %}

templates/news/search.html
{% extends 'base/base.html' %}
{% load static %}
{% load news_template_filters %}
{% block title %}
  新闻搜索
{% endblock %}
{% block link %}
  <link rel="stylesheet" href="{% static 'css/news/search.css' %}">
{% endblock %}

{% block main_contain %}
  <!-- main-contain start  -->
  <div class="main-contain ">
    <!-- search-box start -->
    <div class="search-box">
      <form action="" style="display: inline-flex;">
        <input type="search" placeholder="请输入要搜索的内容" name="q" class="search-control">
        <input type="submit" value="搜索" class="search-btn">
      </form>
      <!-- 可以用浮动 垂直对齐 以及 flex  -->
    </div>
    <!-- search-box end -->
    <!-- content start -->
    <div class="content">
      {# 显示搜索结果 #}
      {% if not show_hot %}
        <!-- search-list start -->
        <div class="search-result-list">
          <h2 class="search-result-title" style="font-weight: 700;color: #ff6620;">
            搜索结果
            <span>{{ page.paginator.num_pages|default:0 }}</span> 页
          </h2>
          <ul class="news-list">
            {# 导入自带高亮功能 #}
            {% load highlight %}
            {% for news in page.object_list %}
              <li class="news-item clearfix">
                <a href="{% url 'news:news_detail' news.id %}" class="news-thumbnail" target="_blank">
                  <img src="{{ news.object.image_url }}" alt="">
                </a>
                <div class="news-content">
                  <h4 class="news-title">
                    <a href="{% url 'news:news_detail' news.id %}">{% highlight news.title with query %}</a>
                  </h4>
                  <p class="news-details">{% highlight news.digest with query %}</p>
                  <div class="news-other">
                    <span class="news-type">{{ news.object.tag.name }}</span>
                    <span class="news-time">{{ news.object.update_time }}</span>
                    <span class="news-author">{% highlight news.object.author.username with query %}</span>
                  </div>
                </div>

              </li>
              {# django在for循环中放置了一个内置模板标记，如果for循环中没有任何对象，则运行{% empty %}模板标记内的代码 #}
            {% empty %}
              <li class="news-item clearfix">
                <p>没有找到你想要的找的内容.</p>
              </li>
            {% endfor %}
          </ul>
        </div>

        <!-- search-list end -->
        {# 显示热门 #}
      {% else %}
        <!-- news-contain start -->
        <div class="news-contain">
          <div class="hot-recommend-list">
            <h2 class="hot-recommend-title">热门推荐</h2>
            <ul class="news-list">
              {# 自己做的分页，没有经过检索，不用object #}
              {% for hotnews in page %}
                <li class="news-item clearfix">
                  <a href="{% url 'news:news_detail' hotnews.news.id %}" class="news-thumbnail">
                    <img src="{{ hotnews.news.image_url }}">
                  </a>
                  <div class="news-content">
                    <h4 class="news-title">
                      <a href="{% url 'news:news_detail' hotnews.news_id %}">{{ hotnews.news.title }}</a>
                    </h4>
                    <p class="news-details">{{ hotnews.news.digest }}</p>
                    <div class="news-other">
                      <span class="news-type">{{ hotnews.news.tag.name }}</span>
                      <span class="news-time">{{ hotnews.update_time }}</span>
                      <span class="news-author">{{ hotnews.news.author.username }}</span>
                    </div>
                  </div>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <!-- news-contain end -->
      {% endif %}
      <!-- Pagination start-->
      {# 底部页码条 #}
      <div class="page-box" id="pages">
        <div class="pagebar" id="pageBar">
          <a class="al">{{ page.paginator.count|default:0 }}条</a>
          <!-- prev page start-->
          {# 是否有上一页 #}
          {% if page.has_previous %}
            {% if query %}
              <a href="{% url 'news:news_search' %}?q={{ query }}&page={{ page.previous_page_number }}"
                 class="prev">上一页</a>
            {% else %}
              <a href="{% url 'news:news_search' %}?page={{ page.previous_page_number }}" class="prev">上一页</a>
            {% endif %}
          {% endif %}
          <!-- prev page end-->

          <!-- page bar start-->
        {# 列出所有 #}
          {% if page.has_previous or page.has_next %}
            {% for n in page|page_bar %}
              {% if query %}
                {% if n == '...' %}
                  <span class="point">{{ n }}</span>
                {% else %}
                  {# 如果是当前页 #}
                  {% if n == page.number %}
                    <span class="sel">{{ n }}</span>
                  {% else %}
                    <a href="{% url 'news:news_search' %}?page={{ n }}&q={{ query }}">{{ n }}</a>
                  {% endif %}
                {% endif %}
              {% else %}
                {% if n == '...' %}
                  <span class="point">{{ n }}</span>
                {% else %}
                  {% if n == page.number %}
                    <span class="sel">{{ n }}</span>
                  {% else %}
                    <a href="{% url 'news:news_search' %}?page={{ n }}">{{ n }}</a>
                  {% endif %}
                {% endif %}
              {% endif %}
            {% endfor %}
          {% endif %}
          <!-- page bar end-->

          <!-- next page start-->
          {% if page.has_next %}
            {% if query %}
              <a href="{% url 'news:news_search' %}?q={{ query }}&page={{ page.next_page_number }}" class="prev">下一页</a>
            {% else %}
              <a href="{% url 'news:news_search' %}?page={{ page.next_page_number }}" class="prev">下一页</a>
            {% endif %}
          {% endif %}
          <!-- next page end-->
        </div>
      </div>
      <!-- Pagination end-->
    </div>
    <!-- content end -->
  </div>
  <!-- main-contain  end -->
{% endblock %}